server:
  port: 8080

spring:
  application:
    name: trip-craft-server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trip_craft?useUnicode=true&characterEncoding=utf8mb4&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root

mybatis-plus:
  configuration:
    # 数据库下划线字段自动映射为驼峰属性
    map-underscore-to-camel-case: true
  global-config:
    banner: false
